### ISSUE TITLE
Disabled prop not working as expected

### ISSUE THREAD

**Issue by gcottrell1** [ef-carbon/react-native-async-button#11]
I'm changing the disabled prop based on some other variable and the button is not changing between enabled/disabled as expected. I'm experiencing the following:

`<AsyncButton disabled={var} .../>`
1. on first render `var=true` the button is disabled
2. When `var=false` the button is still disabled

Also I've experienced the following flow:
1. on first render `var=false` the button is enabled
2. `var=true` the button is disabled
3. `var=false` the button is still disabled

I have a feeling that the problem lies here https://github.com/ef-carbon/react-native-async-button/blob/6c177ceacb27c879365b56d9457927761fb8cc4d/lib/AsyncButton/Component.tsx#L237

If I'm right, doesn't this line mean that if the disabled is set on the state then this will override the disabled prop?

I'm thinking if we had `disabledInternal` and `disabledExternal` on the state we could prevent any overriding of the variables and then have: 
```
private get () {
  if (this.state.disabledInternal || this.state.disabledExternal) return true;
  return false;
}
```
and use this to determine if the button should be rendered in a view/TouchableOpacity

Will put up a PR if you think this is right

**Comment by mattyclarkson** [comment]
The internal `disabled` state is really to signify that the button is processing; this is to prevent new taps when a inflight operation has already been fired off. Essentially, it is used to decide if we should add the `TouchableHighlight` around the actual component, see [L242-L252](https://github.com/ef-carbon/react-native-async-button/blob/6c177ceacb27c879365b56d9457927761fb8cc4d/lib/AsyncButton/Component.tsx#L242-L252). It would make more sense, rather than having an internal disabled state, check the `processing` state in the render function:

```ts
const element = this.renderElement();
const tappable = !this.props.disabled && !this.processing;
if (!tappable) {
  return (<View style={[styles.container, this.props.style]}>{element}</View>)
}
return (
        <TouchableHighlight
          style={[styles.container, this.props.style]}
          underlayColor='transparent'
          onPress={this.handlePress}
        >
          {element}
        </TouchableHighlight>
      );
```

Having looked at the code, it could do with a bit of a general clean up in any case. Top of the head thoughts:
  * The split out property interfaces are not needed now as you can use `Exclude` from TypeScript `2.8` to do the equivalent.
  * Use `TouchableOpacity` rather than `TouchableHighlight`
  * Add theme support so that we use the opacity from the theme for the `TouchableOpacity`
  * Add a `disabled` getter that aliases `this.props.disabled` for ease of use
  * Pass `this.disabled` to each of the component callbacks by using `Component<boolean>` (see #10)
  * *Could* add a `DisabledComponent` that overrides all other components when the disable property is set. The `renderComponent` would have a `if (this.disabled && this.props.DisabledComponent) { return this.renderDisabledComponent()` at the start.

Might be worth implementing them if getting involved with the code to make some changes, or not 🤷‍♂️
